server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://124.71.157.165:3306/yunshanfu?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root

  #jpa配置
  jpa:
    database: MYSQL
    #是否打印SQL语句
    show-sql: true
    #是否自定创建或者更改表
    generate-ddl: false

  #javaMailSender  邮件发送的配置
  mail:
    host: smtp.qq.com
    #发送邮件的人
    username:
    #QQ邮箱的授权码
    password: bcyjzoucvaougiia
    smtp.auth: true
    smpt.starttls.senable: true
    smtp.starttls.required: true
    default-encoding: utf-8

#数据库配置信息
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.qf.pojo